name: Post A New Wanker
description: I wanna post a new wanker
title: "[New Wanker]: "
labels:
  - "Wanker"
assignees:
  - "WankersArchive"
body:
  - type: checkboxes
    attributes:
      label: Claim
      options:
        - label: I have evidence that someone is a wanker and I can confirm the accuracy of this information.
          required: true
  - type: input
    attributes:
      label: Name
  - type: input
    attributes:
      label: Location
  - type: input
    attributes:
      label: Occupation
  - type: input
    attributes:
      label: Affiliation
  - type: input
    attributes:
      label: DateTime
  - type: input
    attributes:
      label: Description
  - type: markdown
    attributes:
      value: "Please put your evidence here. Thank you very much for your sincere post."
  - type: textarea
    attributes:
      label: Contents
